### ISSUE TITLE
Unsuccesful synced resource but ready composition

### ISSUE THREAD

**Issue by modulo1982** [crossplane-contrib/function-auto-ready#114]
When a Composition is created and all of its subresources eventually become Ready, the function-auto-ready sets the Ready condition on the Composition accordingly.

If then a change is made to the composition that causes syncing of a subresource to fail. The composition remains ready because the subresource remains ready.

However, if the Composition is later updated in a way that causes one of its subresources to fail syncing, the Composition continues to report as Ready. 

I believe this is incorrect behavior. A Composition should not be considered Ready if any of its subresources are NotReady or not successfully synced.

Crossplane trace:

```
LambdaFunction/lets-doit-dd7z5                                       True     True    Available
├─ Alias/customize-user-details-dd7z5-qbsdk                          False    True    ReconcileError: ...ception: Additional version weight must be less than 100 %
└─  Function/informatiebeveiliging-customize-user-details            True     True    Available
```

Status:

```
conditions:
  -reason: Available
    status: "True"
    type: Ready
-  status: "False"
    type: Synced
    reason: AsyncUpdateFailure
    message: 'async update failed: failed to update the resource: error Lambda: UpdateAlias, https response error StatusCode: 400, InvalidParameterValueException: Additional version weight must be less than 100 % 
```
