### ISSUE TITLE
Never Ready When Creating Env Config

### ISSUE THREAD

**Issue by reedjosh** [crossplane-contrib/function-auto-ready#29]
### What happened?
I created a few things with a composition pipeline and ended with auto-ready.

One of the things I created was an environment configuration.

Because the env config never really gets a status, fn auto ready never seems to do anything.

``` yaml
  conditions:
  - lastTransitionTime: "2024-05-06T13:17:39Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-05-06T13:19:52Z"
    message: 'Unready resources: cluster-josh-x1-env'
    reason: Creating
    status: "False"
    type: Ready
```

Any chance we could either tell fn-auto-ready of a list of resources to ignore, and or make fn-auto ready schema aware of objects. Particularly env-configs since it is a known k8s resource?

Thanks!

### How can we reproduce it?
Create stuff without a status.

### What environment did it happen in?
Function version: v0.2.1

**Comment by tomaszkiewicz** [comment]
+1, I have similar case when creating ProviderConfig - they don't provide any conditions and seems function-auto-ready ignores them.

**Comment by tomaszkiewicz** [comment]
@reedjosh I'm created a quick fix for that, tested with `ProvideConfigs`, but should work for any resource without `conditions` specified in `status`.

You can test that by replacing your `function-auto-ready` definition with my build of the function:

```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-auto-ready
spec:
  package: xpkg.upbound.io/luktom/function-auto-ready:v0.2.2
```

Let me know if this is what you needed :)
